### ISSUE TITLE
BitBucket docker: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR and its subdirectories.

### ISSUE THREAD

**Issue by bennymeade** [thomasleveil/docker-testcafe#2]
Hello @thomasleveil, 
I'm trying to run this in BitBucket pipelines, using the following **bitbucket-pipelines.yml** script:

```
image: tomdesinto/testcafe
pipelines:
  default:
    - step:
        name: Run tests
        deployment: test 
        script:
          - pwd
          - ls -al
          - docker build -t tomdesinto/testcafe .
          - docker run --rm -i -v /my/testcafe/tests/:/tests tomdesinto/testcafe:latest testcafe 'chromium --no-sandbox' '/tests/*.test.js'
        services:
          - docker

```

But on the docker run step this error is thrown:
```
+ docker run --rm -i -v /my/testcafe/tests/:/tests tomdesinto/testcafe:latest testcafe 'chromium --no-sandbox' '/tests/*.test.js'
docker: Error response from daemon: authorization denied by plugin pipelines: -v only supports $BITBUCKET_CLONE_DIR and its subdirectories.
```
I tried removing the -v (Bind mount a volume) reference but that also throws an error; docker: invalid reference format.

How can I overcome this?
